// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../time/models.js";

export class Todo {
    "Id": number;
    "Title": string;
    "Desc": string;
    "Tags": string;
    "Date": string;

    /**
     * 这个Field将在Insert时自动赋值为当前时间
     */
    "Create": time$0.Time;
    "Update": time$0.Time;

    /** Creates a new Todo instance. */
    constructor($$source: Partial<Todo> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = 0;
        }
        if (!("Title" in $$source)) {
            this["Title"] = "";
        }
        if (!("Desc" in $$source)) {
            this["Desc"] = "";
        }
        if (!("Tags" in $$source)) {
            this["Tags"] = "";
        }
        if (!("Date" in $$source)) {
            this["Date"] = "";
        }
        if (!("Create" in $$source)) {
            this["Create"] = null;
        }
        if (!("Update" in $$source)) {
            this["Update"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Todo instance from a string or object.
     */
    static createFrom($$source: any = {}): Todo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Todo($$parsedSource as Partial<Todo>);
    }
}
