// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

export function Add(title: string, desc: string, date: string, tags: string): $CancellablePromise<string> {
    return $Call.ByID(2727250855, title, desc, date, tags);
}

export function Delete(id: number): $CancellablePromise<string> {
    return $Call.ByID(2011412535, id);
}

export function List(): $CancellablePromise<model$0.Todo[]> {
    return $Call.ByID(3632311716).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = model$0.Todo.createFrom;
const $$createType1 = $Create.Array($$createType0);
